version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  app:
    build:
      context: .
    image: invoices-app
    env_file: ./.env
    ports:
      - $APP_PORT:$APP_PORT
    environment:
        DB_USER: $DB_USER
        DB_PASSWORD: $DB_PASSWORD
        DB_NAME: $DB_NAME
        DB_HOST: mysqldb
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes: 
  db-config:
  db-data: